---

- name: install ansible
  yum: name=ansible state=present

- name: disable tty requirement for ec2-user
  lineinfile:
    line: Defaults:ec2-user !requiretty
    dest: /etc/sudoers
    state: present

- name: enable ansible pipelining
  lineinfile:
    line: pipelining = True
    dest: /etc/ansible/ansible.cfg
    state: present

...
